/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.apis

import com.tink.rest.models.ActionableInsight
import com.tink.rest.models.ArchivedInsight
import com.tink.rest.models.SelectInsightActionRequest
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.PUT

@JvmSuppressWildcards
interface ActionableInsightApi {
    /**
     * Archive an insight
     * Move an active insight to an archived state.
     * @param id The identifier of the insight that should be archived. (required)
     */
    @PUT("/api/v1/insights/{id}/archive")
    suspend fun archiveInsight(
        @retrofit2.http.Path("id") id: String
    ): Response<Unit>
    /**
     * List insights
     * Lists all insights for the user.
     */
    @GET("/api/v1/insights")
    suspend fun list(): List<ActionableInsight>
    /**
     * List archived insights
     * Lists all archived insights for the user.
     */
    @GET("/api/v1/insights/archived")
    suspend fun listArchivedInsights(): List<ArchivedInsight>
    /**
     * Take action on an insight
     * Report a user action on an insight and move the insight to an archived state.
     * @param body The insight action that should be selected. (required)
     */
    @POST("/api/v1/insights/action")
    suspend fun selectInsightAction(
        @retrofit2.http.Body body: SelectInsightActionRequest
    ): Response<Unit>
}
