/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id The ID of the transaction.
 * @property amount The transaction amount.
 * @property dispensableAmount The dispensable amount. This amount will e.g. be reduced if the account it belongs to has ownership set to 50%.
 * @property date Date of the transaction expressed as UTC epoch timestamp in milliseconds.
 * @property description Description of the transaction.
 * @property categoryCode Category code.
 * @property accountId The ID of the account this transaction belongs to.
 */
@JsonClass(generateAdapter = true)
data class BudgetTransaction(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: CurrencyDenominatedAmount? = null,
    @Json(name = "dispensableAmount") @field:Json(name = "dispensableAmount") var dispensableAmount: CurrencyDenominatedAmount? = null,
    @Json(name = "date") @field:Json(name = "date") var date: Long = 0,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "categoryCode") @field:Json(name = "categoryCode") var categoryCode: String? = null,
    @Json(name = "accountId") @field:Json(name = "accountId") var accountId: String? = null
)
