/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property budgetSpecification The budget.
 * @property budgetPeriod The current running period.
 */
@JsonClass(generateAdapter = true)
data class BudgetSummary(
    @Json(name = "budgetSpecification") @field:Json(name = "budgetSpecification") var budgetSpecification: Budget? = null,
    @Json(name = "budgetPeriod") @field:Json(name = "budgetPeriod") var budgetPeriod: BudgetPeriod? = null
)
