/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property budgetSpecification The budget.
 * @property budgetPeriods List of budget periods.
 * @property start First period start expressed as UTC epoch timestamp in milliseconds.
 * @property end Last period end expressed as UTC epoch timestamp in milliseconds.
 * @property totalSpentAmount Total amount spent within the listed periods.
 * @property averageSpentAmount Average period spending for the listed periods.
 */
@JsonClass(generateAdapter = true)
data class BudgetDetailsResponse(
    @Json(name = "budgetSpecification") @field:Json(name = "budgetSpecification") var budgetSpecification: Budget? = null,
    @Json(name = "budgetPeriods") @field:Json(name = "budgetPeriods") var budgetPeriods: List<BudgetPeriod>? = null,
    @Json(name = "start") @field:Json(name = "start") var start: ZonedDateTime? = null,
    @Json(name = "end") @field:Json(name = "end") var end: ZonedDateTime? = null,
    @Json(name = "totalSpentAmount") @field:Json(name = "totalSpentAmount") var totalSpentAmount: CurrencyDenominatedAmount? = null,
    @Json(name = "averageSpentAmount") @field:Json(name = "averageSpentAmount") var averageSpentAmount: CurrencyDenominatedAmount? = null
)
