/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property start Period start expressed as UTC epoch timestamp in milliseconds.
 * @property end Period end expressed as UTC epoch timestamp in milliseconds.
 * @property spentAmount Period spent amount.
 */
@JsonClass(generateAdapter = true)
data class BudgetPeriod(
    @Json(name = "start") @field:Json(name = "start") var start: Long = 0,
    @Json(name = "end") @field:Json(name = "end") var end: Long = 0,
    @Json(name = "spentAmount") @field:Json(name = "spentAmount") var spentAmount: CurrencyDenominatedAmount? = null
)
