/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property budgetSpecification The budget.
 * @property budgetPeriods The current running period.
 */
@JsonClass(generateAdapter = true)
data class BudgetSummary(
    @Json(name = "budgetSpecification") @field:Json(name = "budgetSpecification") var budgetSpecification: Budget? = null,
    @Json(name = "budgetPeriods") @field:Json(name = "budgetPeriods") var budgetPeriods: BudgetPeriod? = null
)
