/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property categorizationList A list of new categories and the transactions&#39; IDs
 */
@JsonClass(generateAdapter = true)
data class CategorizeTransactionsListRequest(
    @Json(name = "categorizationList") @field:Json(name = "categorizationList") var categorizationList: List<CategorizeTransactionsRequest>
)
