/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property allowed
 * @property description
 * @property id
 * @property messages
 * @property sessionType
 */
@JsonClass(generateAdapter = true)
data class Client(
    @Json(name = "allowed") @field:Json(name = "allowed") var allowed: Boolean? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "messages") @field:Json(name = "messages") var messages: List<ClientMessage>? = null,
    @Json(name = "sessionType") @field:Json(name = "sessionType") var sessionType: Client.SessionTypeEnum? = null
) {
    /**
     * Values: MOBILE, WEB, LINK, OAUTH
     */
    @JsonClass(generateAdapter = false)
    enum class SessionTypeEnum(val value: String) {
        @Json(name = "MOBILE") MOBILE("MOBILE"),
        @Json(name = "WEB") WEB("WEB"),
        @Json(name = "LINK") LINK("LINK"),
        @Json(name = "OAUTH") OAUTH("OAUTH")
    }
}
