/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @param ownerAccountId The identifier of the source account that this beneficiary should be added to.
 * @param credentialsId The ID of the [Credentials] used to add the beneficiary. Note that you can send in a different ID here than the credentials ID to which the account belongs. This functionality exists to support the case where you may have double credentials for one financial institution, due to PSD2 regulations.
 * @param name The name chosen by the user for this beneficiary.
 * @param accountNumberType The type of the [accountNumber] that this beneficiary has.
 * @param accountNumber The account number for the beneficiary. The structure of this field depends on the [accountNumberType].
 */
@JsonClass(generateAdapter = true)
data class CreateBeneficiaryRequest(
    @Json(name = "ownerAccountId") @field:Json(name = "ownerAccountId") var ownerAccountId: String,
    @Json(name = "credentialsId") @field:Json(name = "credentialsId") var credentialsId: String,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "accountNumberType") @field:Json(name = "accountNumberType") var accountNumberType: String,
    @Json(name = "accountNumber") @field:Json(name = "accountNumber") var accountNumber: String
)
