/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property market Market specific code for the user as a ISO 3166-1 country code.
 * @property locale Locale for the user. Defaults to default locale for the user&#39;s market.
 * @property externalUserId Optional external user ID for the created user.
 */
@JsonClass(generateAdapter = true)
data class CreateUserRequest(
    @Json(name = "market") @field:Json(name = "market") var market: String,
    @Json(name = "locale") @field:Json(name = "locale") var locale: String? = null,
    @Json(name = "external_user_id") @field:Json(name = "external_user_id") var externalUserId: String? = null
)
