/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property credentials A list of credentials
 */
@JsonClass(generateAdapter = true)
data class CredentialsListResponse(
    @Json(name = "credentials") @field:Json(name = "credentials") var credentials: List<Credentials>? = null
)
