/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type The action type
 */
@JsonClass(generateAdapter = true)
data class InsightActionData(
    @Json(name = "type") @field:Json(name = "type") var type: InsightActionData.TypeEnum? = null
) {
    /**
     * The action type
     * Values: ACKNOWLEDGE, DISMISS, VIEW_BUDGET, CREATE_TRANSFER, VIEW_TRANSACTION, CATEGORIZE_EXPENSE, VIEW_TRANSACTIONS, CATEGORIZE_TRANSACTIONS, VIEW_TRANSACTIONS_BY_CATEGORY, VIEW_EXPECTED_AND_ACTUAL_AMOUNT
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ACKNOWLEDGE") ACKNOWLEDGE("ACKNOWLEDGE"),
        @Json(name = "DISMISS") DISMISS("DISMISS"),
        @Json(name = "VIEW_BUDGET") VIEW_BUDGET("VIEW_BUDGET"),
        @Json(name = "CREATE_TRANSFER") CREATE_TRANSFER("CREATE_TRANSFER"),
        @Json(name = "VIEW_TRANSACTION") VIEW_TRANSACTION("VIEW_TRANSACTION"),
        @Json(name = "CATEGORIZE_EXPENSE") CATEGORIZE_EXPENSE("CATEGORIZE_EXPENSE"),
        @Json(name = "VIEW_TRANSACTIONS") VIEW_TRANSACTIONS("VIEW_TRANSACTIONS"),
        @Json(name = "CATEGORIZE_TRANSACTIONS") CATEGORIZE_TRANSACTIONS("CATEGORIZE_TRANSACTIONS"),
        @Json(name = "VIEW_TRANSACTIONS_BY_CATEGORY") VIEW_TRANSACTIONS_BY_CATEGORY("VIEW_TRANSACTIONS_BY_CATEGORY"),
        @Json(name = "VIEW_EXPECTED_AND_ACTUAL_AMOUNT") VIEW_EXPECTED_AND_ACTUAL_AMOUNT("VIEW_EXPECTED_AND_ACTUAL_AMOUNT")
    }
}
