/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property budgetSpecifications List of budgets.
 */
@JsonClass(generateAdapter = true)
data class ListBudgetSpecificationsResponse(
    @Json(name = "budgetSpecifications") @field:Json(name = "budgetSpecifications") var budgetSpecifications: List<Budget>? = null
)
