/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property beneficiaries A list of all beneficiaries for all the accounts belonging to the authenticated user.
 */
@JsonClass(generateAdapter = true)
data class ListBeneficiariesResponse(
    @Json(name = "beneficiaries") val beneficiaries: List<Beneficiary>
)
