/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID
import org.threeten.bp.ZonedDateTime

/**
 * @property created The timestamp of the creation of the operation.
 * @property id The ID of this operation.
 * @property status The status of the operation. CANCELLED, FAILED and EXECUTED are all endstates.
 * @property statusMessage The status message of the operation
 * @property type The type of operation.
 * @property underlyingId The ID of the actual transfer.
 * @property updated The timestamp of the last update of the operation.
 * @property userId The ID of the user making the operation.
 * @property credentialsId The ID of the Credentials used to make the operation.
 */
@JsonClass(generateAdapter = true)
data class SignableOperation(
    @Json(name = "created") @field:Json(name = "created") var created: ZonedDateTime? = null,
    @Json(name = "id") @field:Json(name = "id") var id: UUID? = null,
    @Json(name = "status") @field:Json(name = "status") var status: StatusEnum? = null,
    @Json(name = "statusMessage") @field:Json(name = "statusMessage") var statusMessage: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: TypeEnum? = null,
    @Json(name = "underlyingId") @field:Json(name = "underlyingId") var underlyingId: UUID? = null,
    @Json(name = "updated") @field:Json(name = "updated") var updated: ZonedDateTime? = null,
    @Json(name = "userId") @field:Json(name = "userId") var userId: UUID? = null,
    @Json(name = "credentialsId") @field:Json(name = "credentialsId") var credentialsId: UUID? = null
) {
    /**
     * The status of the operation. CANCELLED, FAILED and EXECUTED are all endstates.
     * Values: CREATED, EXECUTING, AWAITING_CREDENTIALS, CANCELLED, FAILED, EXECUTED, AWAITING_THIRD_PARTY_APP_AUTHENTICATION
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "CREATED") CREATED("CREATED"),
        @Json(name = "EXECUTING") EXECUTING("EXECUTING"),
        @Json(name = "AWAITING_CREDENTIALS") AWAITING_CREDENTIALS("AWAITING_CREDENTIALS"),
        @Json(name = "CANCELLED") CANCELLED("CANCELLED"),
        @Json(name = "FAILED") FAILED("FAILED"),
        @Json(name = "EXECUTED") EXECUTED("EXECUTED"),
        @Json(name = "AWAITING_THIRD_PARTY_APP_AUTHENTICATION") AWAITING_THIRD_PARTY_APP_AUTHENTICATION("AWAITING_THIRD_PARTY_APP_AUTHENTICATION")
    }
    /**
     * The type of operation.
     * Values: TRANSFER
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "TRANSFER") TRANSFER("TRANSFER")
    }
}
