/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property canTransfer Whether or not the source account can transfer money towards the destination account.
 */
@JsonClass(generateAdapter = true)
data class SourceDestinationValidation(
    @Json(name = "canTransfer") @field:Json(name = "canTransfer") var canTransfer: Boolean
)
