/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property key
 * @property value
 */
@JsonClass(generateAdapter = true)
data class StringDoublePair(
    @Json(name = "key") @field:Json(name = "key") var key: String? = null,
    @Json(name = "value") @field:Json(name = "value") var value: Double? = null
)
