/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property status The transfer status.
 * @property statusMessage A message with additional information regarding the current status of the transfer.
 * @property id The transfer unique identifier.
 * @property destinationUri The destination account or recipient of the transfer, in the form of a uri.
 * @property sourceUri The source account of the transfer, in the form of a uri. Only returned if available from the bank response.
 */
@JsonClass(generateAdapter = true)
data class TransferResponse(
    @Json(name = "status") @field:Json(name = "status") var status: StatusEnum,
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "destinationUri") @field:Json(name = "destinationUri") var destinationUri: String,
    @Json(name = "sourceUri") @field:Json(name = "sourceUri") var sourceUri: String,
    @Json(name = "statusMessage") @field:Json(name = "statusMessage") var statusMessage: String? = null
) {
    /**
     * The transfer status.
     * Values: AWAITING_CREDENTIALS, CREATED, SENT, FAILED, CANCELLED, UNKNOWN
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "AWAITING_CREDENTIALS") AWAITING_CREDENTIALS("AWAITING_CREDENTIALS"),
        @Json(name = "CREATED") CREATED("CREATED"),
        @Json(name = "SENT") SENT("SENT"),
        @Json(name = "FAILED") FAILED("FAILED"),
        @Json(name = "CANCELLED") CANCELLED("CANCELLED"),
        @Json(name = "UNKNOWN") UNKNOWN("UNKNOWN")
    }
}
