/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Tink API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.tink.rest.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property date The date the transaction part was created.
 * @property id The ID of the transaction part.
 * @property lastModified The date the transaction part was last modified.
 * @property categoryId The category of the transaction part.
 * @property counterpartId The id of the counterpart. The counterpart is a transaction part in another transaction
 * @property counterpartTransactionId The ID of the transaction containing the counterpart.
 * @property counterpartDescription The description of the transaction containing the counterpart.
 * @property amount The amount of the transaction part.
 * @property counterpartTransactionAmount The amount of the transaction containing the counterpart.
 */
@JsonClass(generateAdapter = true)
data class TransactionPart(
    @Json(name = "date") @field:Json(name = "date") var date: Long,
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "lastModified") @field:Json(name = "lastModified") var lastModified: Long,
    @Json(name = "categoryId") @field:Json(name = "categoryId") var categoryId: String,
    @Json(name = "counterpartId") @field:Json(name = "counterpartId") var counterpartId: String,
    @Json(name = "counterpartTransactionId") @field:Json(name = "counterpartTransactionId") var counterpartTransactionId: String,
    @Json(name = "counterpartDescription") @field:Json(name = "counterpartDescription") var counterpartDescription: String,
    @Json(name = "amount") @field:Json(name = "amount") var amount: Double,
    @Json(name = "counterpartTransactionAmount") @field:Json(name = "counterpartTransactionAmount") var counterpartTransactionAmount: Double
)
